
# ---
# generated by js2coffee 2.1.0

Template.edit.helpers
  title: ->
    post_id = Router.current().params.post_id
    console.log 'post_id:',post_id
    post = Posts.findOne({_id: post_id})
    console.log 'post',post
    if post
       post.title

  description: ->
    post_id = Router.current().params.post_id
    post = Posts.findOne({_id: post_id})
    if post
      post.description

Template.edit.events
  'click .submit': (e,t) ->
    e.preventDefault()
    # currentPostId = @_id
    # console.log 'currentPostId',currentPostId
    post_id = Router.current().params.post_id
    console.log 'this:',post_id
    postProperties = 
      title: t.find('[name=title]').value
      description: t.find('[name=description]').value
      updated_at: new Date()

    console.log 'postProperties:', postProperties
    update_post =Posts.update post_id, { $set: postProperties }
    console.log 'update_post', update_post
    Router.go 'posts'
    #   if error
    #     # display the error to the user
    #     alert error.reason
    #   else
    #     Router.go 'posts', _id: currentPostId
    #   return
    # return
# console.log 'postProperties',postProperties
  'click .delete': (e) ->
    e.preventDefault()
    if confirm('Delete this post?')
      post_id = Router.current().params.post_id
      Posts.remove post_id
      Router.go 'posts'
    return
